### ISSUE TITLE
hover interactions

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.com#13]
Right now, hovering over clickables does nothing, or is styled poorly (notably `<a />` elements)

Buttons should probably get a drop shadow/slight overlay when hovered, and similar for any links

**Comment by bobheadxi** [comment]
@srijonsaha see https://daneden.github.io/animate.css/ for some classes you can add on-hover for animations, if you dont feel thats excessive!

**Comment by srijonsaha** [comment]
Those animations are bit too much for buttons and links.
