### ISSUE TITLE
add /latest redirect path for social media campaigns

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/ubclaunchpad.com#190]
We can use the `/latest` path as our custom link shortener. This path should handle redirects to the latest Medium blog post.

Related PR commit: https://github.com/ubclaunchpad/docs/pull/137/commits/41f06b68bc7b389fdfb84d3536d7db82be40769c

**Comment by bobheadxi** [comment]
@andrewzulaybar I transferred this to https://github.com/ubclaunchpad/ubclaunchpad.com because redirects are configured here :)

**Comment by andrewzulaybar** [comment]
@bobheadxi ah yes, my bad 😅 thanks for moving it here!
