### ISSUE TITLE
add sponsors info

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.com#30]
We'll need all the sponsors from this year! Just add it to [`src/config.ts`](https://github.com/ubclaunchpad/new/blob/master/src/config.ts#L307)

* Documentation: https://ubclaunchpad.github.io/new/config/globals.html#clubsponsor

/cc @ubclaunchpad/strategy 

related: #27

**Comment by ghost** [comment]
Added
