### ISSUE TITLE
join: reveal modal on position click with description

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.com#49]
https://ubclaunchpad.github.io/new#join

Right now, positions open the application link directly - IMO they should open a modal with a short description, with a button to go to the application from there.

/cc @cowjuh , @srijonsaha , @RachitMalik12 for thoughts

If this sounds good, we'll need to finalize on a modal design for #14 and repurpose that here

**Comment by srijonsaha** [comment]
What information are you putting in the modal? I think having a decent amount of information about the role and the application process in the modal would be a good reason to have the modal (like some of the information that gets put into the application google doc itself). But if we are just putting one or two lines and a button to link to the application with details then it doesn't make much sense to have a modal pop up personally.

**Comment by bobheadxi** [comment]
While we might end up slightly duplicating the information on the google form, I imagine the primary use case for section would be linking people directly to https://ubclaunchpad.github.io/new/#join - and redirecting you immediately away from our website to a google form seems rather abrupt.

The only information at the moment I'm thinking of having in there is the [description](https://sourcegraph.com/github.com/ubclaunchpad/new/-/blob/src/config.ts#L65), and maybe FAQ questions relevant to the position (both sourced from the old website)

**Comment by bobheadxi** [comment]
#74 and #45 lays out a promising start to more flexible modals. That said, feature is not really a priority right now, since we'll likely launch with `applicationsOpen: false`

**Comment by bobheadxi** [comment]
let's forgo the popup in favour of https://github.com/ubclaunchpad/docs/pull/103
