### ISSUE TITLE
Add iOS and Android icons to project modal and config

### ISSUE THREAD

**Issue by RachitMalik12** [ubclaunchpad/ubclaunchpad.com#62]

**Comment by bobheadxi** [comment]
I would probably have this in addition to `website`, ie:

```ts
type DownloadType = 'ios' | 'android'
```

```ts
download?: string;
downloadType?: DownloadType;
```

I think it's not entirely unreasonable to have both a website and have your app be available in aapp store (I dont think any project has done this yet, but who knows?)
