### ISSUE TITLE
safari: cisco logo is weird

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.com#88]
15" macbook pro, ipad 9.7

![image](https://user-images.githubusercontent.com/23356519/80287437-7b73ad00-86e6-11ea-9ed4-0914acc0b21b.png)

**Comment by rwblickhan** [comment]
I saw it on Safari on 15" MacBook Pro

**Comment by bobheadxi** [comment]
confirmed this is specifically a safari issue
