### ISSUE TITLE
add icons to Highlights 🍔 🦅 🤖 

### ISSUE THREAD

**Issue by suujia** [ubclaunchpad/ubclaunchpad.com#89]
![image](https://user-images.githubusercontent.com/22860428/80287498-4e77c800-86ef-11ea-97fe-131cf37f9233.png)

**Comment by bobheadxi** [comment]
I actually feel like images might be nice here! The website has a distinct lack of real humans

These Medium posts have images we could use - maybe above each section, could add a little thumbnail:

* https://medium.com/ubc-launch-pad-software-engineering-blog/review-of-the-first-month-of-launch-pad-5eddf1c7a095
* https://medium.com/ubc-launch-pad-software-engineering-blog/what-is-ubc-launch-pad-d3bbfe6322dc
